"""empty message

Revision ID: 0a42b3c6224d
Revises: 21f4ca5b1b06
Create Date: 2019-12-24 11:55:11.605151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42b3c6224d'
down_revision = '21f4ca5b1b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('grad_year', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_batter_grad_year'), 'batter', ['grad_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batter_grad_year'), table_name='batter')
    op.drop_column('batter', 'grad_year')
    # ### end Alembic commands ###
