"""added notes to pitch table

Revision ID: 0a8915b088ef
Revises: 48526d5906a5
Create Date: 2020-02-13 15:23:15.308233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8915b088ef'
down_revision = '48526d5906a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('notes', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'notes')
    # ### end Alembic commands ###
