"""pitches table

Revision ID: 1004ac713339
Revises: 1788f9511e8a
Create Date: 2019-11-29 09:50:20.232315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1004ac713339'
down_revision = '1788f9511e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outing_id', sa.Integer(), nullable=True),
    sa.Column('pitch_num', sa.Integer(), nullable=True),
    sa.Column('batter_id', sa.String(length=32), nullable=True),
    sa.Column('batter_hand', sa.String(length=16), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('lead_runner', sa.Integer(), nullable=True),
    sa.Column('time_to_plate', sa.Numeric(), nullable=True),
    sa.Column('pitch_type', sa.Integer(), nullable=True),
    sa.Column('pitch_result', sa.String(length=16), nullable=True),
    sa.Column('hit_spot', sa.Boolean(), nullable=True),
    sa.Column('count_balls', sa.Integer(), nullable=True),
    sa.Column('count_strikes', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('fielder', sa.Integer(), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('out', sa.Integer(), nullable=True),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outing_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitch_batter_hand'), 'pitch', ['batter_hand'], unique=False)
    op.create_index(op.f('ix_pitch_batter_id'), 'pitch', ['batter_id'], unique=False)
    op.create_index(op.f('ix_pitch_count_balls'), 'pitch', ['count_balls'], unique=False)
    op.create_index(op.f('ix_pitch_count_strikes'), 'pitch', ['count_strikes'], unique=False)
    op.create_index(op.f('ix_pitch_fielder'), 'pitch', ['fielder'], unique=False)
    op.create_index(op.f('ix_pitch_hit'), 'pitch', ['hit'], unique=False)
    op.create_index(op.f('ix_pitch_hit_spot'), 'pitch', ['hit_spot'], unique=False)
    op.create_index(op.f('ix_pitch_inning'), 'pitch', ['inning'], unique=False)
    op.create_index(op.f('ix_pitch_lead_runner'), 'pitch', ['lead_runner'], unique=False)
    op.create_index(op.f('ix_pitch_out'), 'pitch', ['out'], unique=False)
    op.create_index(op.f('ix_pitch_outing_id'), 'pitch', ['outing_id'], unique=False)
    op.create_index(op.f('ix_pitch_pitch_num'), 'pitch', ['pitch_num'], unique=False)
    op.create_index(op.f('ix_pitch_pitch_result'), 'pitch', ['pitch_result'], unique=False)
    op.create_index(op.f('ix_pitch_pitch_type'), 'pitch', ['pitch_type'], unique=False)
    op.create_index(op.f('ix_pitch_result'), 'pitch', ['result'], unique=False)
    op.create_index(op.f('ix_pitch_time_to_plate'), 'pitch', ['time_to_plate'], unique=False)
    op.create_index(op.f('ix_pitch_velocity'), 'pitch', ['velocity'], unique=False)
    op.create_index(op.f('ix_user_throws'), 'user', ['throws'], unique=False)
    op.create_index(op.f('ix_user_year'), 'user', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_year'), table_name='user')
    op.drop_index(op.f('ix_user_throws'), table_name='user')
    op.drop_index(op.f('ix_pitch_velocity'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_time_to_plate'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_result'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_pitch_type'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_pitch_result'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_pitch_num'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_outing_id'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_out'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_lead_runner'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_inning'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_hit_spot'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_hit'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_fielder'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_count_strikes'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_count_balls'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_batter_id'), table_name='pitch')
    op.drop_index(op.f('ix_pitch_batter_hand'), table_name='pitch')
    op.drop_table('pitch')
    # ### end Alembic commands ###
