"""try again

Revision ID: 1170b0796ce2
Revises: 515163227457
Create Date: 2019-12-18 10:12:19.328418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1170b0796ce2'
down_revision = '515163227457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch') as batch_op:
        batch_op.drop_column('hit')
        batch_op.drop_column('out')
        batch_op.drop_column('result')
        batch_op.drop_column('hit_or_out')
        batch_op.drop_column('count_balls')
        batch_op.drop_column('count_strikes')
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.add_column('pitch', sa.Column('count_balls', sa.INTEGER(), nullable=True))
    op.add_column('pitch', sa.Column('hit_or_out', sa.VARCHAR(length=8), nullable=True))
    op.add_column('pitch', sa.Column('result', sa.VARCHAR(length=16), nullable=True))
    op.add_column('pitch', sa.Column('out', sa.INTEGER(), nullable=True))
    op.add_column('pitch', sa.Column('hit', sa.BOOLEAN(), nullable=True))
    op.add_column('pitch', sa.Column('count_strikes', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
