"""outings table

Revision ID: 1788f9511e8a
Revises: 6c97008a3a5f
Create Date: 2019-11-27 18:58:02.371803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1788f9511e8a'
down_revision = '6c97008a3a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('opponent', sa.String(length=32), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outing_date'), 'outing', ['date'], unique=False)
    op.create_index(op.f('ix_outing_opponent'), 'outing', ['opponent'], unique=False)
    op.create_index(op.f('ix_outing_season'), 'outing', ['season'], unique=False)
    op.create_index(op.f('ix_outing_user_id'), 'outing', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outing_user_id'), table_name='outing')
    op.drop_index(op.f('ix_outing_season'), table_name='outing')
    op.drop_index(op.f('ix_outing_opponent'), table_name='outing')
    op.drop_index(op.f('ix_outing_date'), table_name='outing')
    op.drop_table('outing')
    # ### end Alembic commands ###
