"""empty message

Revision ID: 1c93cdd10567
Revises: 4acb88ed85ac
Create Date: 2020-06-04 23:40:32.257202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c93cdd10567'
down_revision = '4acb88ed85ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat', sa.Column('ab_result', sa.String(length=32), nullable=True))
    op.add_column('at_bat', sa.Column('fielder', sa.String(length=8), nullable=True))
    op.add_column('at_bat', sa.Column('hit_hard', sa.Boolean(), nullable=True))
    op.add_column('at_bat', sa.Column('inning', sa.Integer(), nullable=True))
    op.add_column('at_bat', sa.Column('notes', sa.String(length=128), nullable=True))
    op.add_column('at_bat', sa.Column('spray_x', sa.Float(), nullable=True))
    op.add_column('at_bat', sa.Column('spray_y', sa.Float(), nullable=True))
    op.add_column('at_bat', sa.Column('traj', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_at_bat_ab_result'), 'at_bat', ['ab_result'], unique=False)
    op.create_index(op.f('ix_at_bat_fielder'), 'at_bat', ['fielder'], unique=False)
    op.create_index(op.f('ix_at_bat_hit_hard'), 'at_bat', ['hit_hard'], unique=False)
    op.create_index(op.f('ix_at_bat_inning'), 'at_bat', ['inning'], unique=False)
    op.create_index(op.f('ix_at_bat_traj'), 'at_bat', ['traj'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_at_bat_traj'), table_name='at_bat')
    op.drop_index(op.f('ix_at_bat_inning'), table_name='at_bat')
    op.drop_index(op.f('ix_at_bat_hit_hard'), table_name='at_bat')
    op.drop_index(op.f('ix_at_bat_fielder'), table_name='at_bat')
    op.drop_index(op.f('ix_at_bat_ab_result'), table_name='at_bat')
    op.drop_column('at_bat', 'traj')
    op.drop_column('at_bat', 'spray_y')
    op.drop_column('at_bat', 'spray_x')
    op.drop_column('at_bat', 'notes')
    op.drop_column('at_bat', 'inning')
    op.drop_column('at_bat', 'hit_hard')
    op.drop_column('at_bat', 'fielder')
    op.drop_column('at_bat', 'ab_result')
    # ### end Alembic commands ###
