"""empty message

Revision ID: 1e3027a12dcc
Revises: 22b4403d0d61
Create Date: 2020-03-18 15:17:06.064118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3027a12dcc'
down_revision = '22b4403d0d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batter') as batch_op:
        batch_op.drop_index('ix_batter_short_name')
        batch_op.drop_column('short_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('short_name', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_batter_short_name', 'batter', ['short_name'], unique=False)
    # ### end Alembic commands ###
