"""empty message

Revision ID: 21f4ca5b1b06
Revises: 60efec4356ee
Create Date: 2019-12-23 17:43:38.910805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f4ca5b1b06'
down_revision = '60efec4356ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch') as batch_op:
        batch_op.add_column(sa.Column('atbat_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_pitch_atbat_id'), ['atbat_id'], unique=False)
        batch_op.create_foreign_key('None', 'at_bat', ['atbat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_index(op.f('ix_pitch_atbat_id'), table_name='pitch')
    op.drop_column('pitch', 'atbat_id')
    # ### end Alembic commands ###
