"""empty message

Revision ID: 22b4403d0d61
Revises: 72f12a3f2661
Create Date: 2020-03-18 12:09:55.197316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b4403d0d61'
down_revision = '72f12a3f2661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season') as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_season_year'), ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_year'), table_name='season')
    op.drop_column('season', 'year')
    # ### end Alembic commands ###
