"""empty message

Revision ID: 2440131a3452
Revises: 6cd1d36fc820
Create Date: 2019-12-18 21:01:25.948501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2440131a3452'
down_revision = '6cd1d36fc820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.drop_index('ix_outing_opponent_id')
        batch_op.drop_column('opponent_id')
        batch_op.drop_column('outing_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outing', sa.Column('outing_id', sa.INTEGER(), nullable=True))
    op.add_column('outing', sa.Column('opponent_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'outing', 'opponent', ['outing_id'], ['id'])
    op.create_index('ix_outing_opponent_id', 'outing', ['opponent_id'], unique=False)
    # ### end Alembic commands ###
