"""empty message

Revision ID: 24d363db59ac
Revises: 1170b0796ce2
Create Date: 2019-12-18 12:00:11.649439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d363db59ac'
down_revision = '1170b0796ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.drop_index('ix_outing_season_id')
        batch_op.drop_column('season_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outing', sa.Column('season_id', sa.INTEGER(), nullable=True))
    op.create_index('ix_outing_season_id', 'outing', ['season_id'], unique=False)
    # ### end Alembic commands ###
