"""Add mascot column to opponents

Revision ID: 2e90bd59c7ae
Revises: b47fcd8d3c7c
Create Date: 2020-06-10 13:27:47.351645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e90bd59c7ae'
down_revision = 'b47fcd8d3c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opponent', sa.Column('mascot', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_opponent_mascot'), 'opponent', ['mascot'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opponent_mascot'), table_name='opponent')
    op.drop_column('opponent', 'mascot')
    # ### end Alembic commands ###
