"""empty message

Revision ID: 411beb54b27b
Revises: d6c6ee5ad7e0
Create Date: 2020-01-08 10:44:06.526657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411beb54b27b'
down_revision = 'd6c6ee5ad7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('current_season', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_season_current_season'), 'season', ['current_season'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_current_season'), table_name='season')
    op.drop_column('season', 'current_season')
    # ### end Alembic commands ###
