"""empty message

Revision ID: 492b04a12351
Revises: 2440131a3452
Create Date: 2019-12-18 21:09:16.248717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492b04a12351'
down_revision = '2440131a3452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.add_column(sa.Column('opponent_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_outing_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_foreign_key("None5", 'opponent', ['opponent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outing', type_='foreignkey')
    op.drop_index(op.f('ix_outing_opponent_id'), table_name='outing')
    op.drop_column('outing', 'opponent_id')
    # ### end Alembic commands ###
