"""add resource table

Revision ID: 49ec4dfb04dc
Revises: 547e80c7173a
Create Date: 2020-05-25 17:53:20.879844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ec4dfb04dc'
down_revision = '547e80c7173a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('article_link', sa.String(length=256), nullable=True),
    sa.Column('video_link', sa.String(length=256), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_description'), 'resource', ['description'], unique=False)
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_index(op.f('ix_resource_description'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
