"""empty message

Revision ID: 4acb88ed85ac
Revises: 49ec4dfb04dc
Create Date: 2020-06-02 14:46:56.165938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acb88ed85ac'
down_revision = '49ec4dfb04dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource') as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=256), nullable=True))
        batch_op.drop_column('file_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('file_data', sa.BLOB(), nullable=True))
    op.drop_column('resource', 'file_path')
    # ### end Alembic commands ###
