"""empty message

Revision ID: 53b5309c617a
Revises: 69cf8f314ee2
Create Date: 2020-01-18 17:53:02.784860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b5309c617a'
down_revision = '69cf8f314ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_index('ix_user_throws')
        batch_op.drop_column('throws')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('throws', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_user_throws', 'user', ['throws'], unique=False)
    # ### end Alembic commands ###
