"""empty message

Revision ID: 547e80c7173a
Revises: 1e3027a12dcc
Create Date: 2020-03-19 14:27:34.262095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547e80c7173a'
down_revision = '1e3027a12dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitcher') as batch_op:
        batch_op.drop_index('ix_pitcher_name')
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_pitcher_name', 'pitcher', ['name'], unique=False)
    # ### end Alembic commands ###
