"""empty message

Revision ID: 5d8630dae920
Revises: 0370de8ec4b6
Create Date: 2020-02-06 16:01:10.324213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8630dae920'
down_revision = '0370de8ec4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video') as batch_op:
        #batch_op.create_index(op.f('ix_video_outing_id'), ['outing_id'], unique=False)
        batch_op.create_foreign_key("None", 'outing', ['outing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_index(op.f('ix_video_outing_id'), table_name='video')
    op.drop_column('video', 'outing_id')
    # ### end Alembic commands ###
