"""add at_bat table

Revision ID: 5ddf3b6ef78f
Revises: 379c683363ea
Create Date: 2019-12-19 19:54:58.440513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddf3b6ef78f'
down_revision = '379c683363ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('at_bat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=True),
    sa.Column('outing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batter_id'], ['batter.id'], ),
    sa.ForeignKeyConstraint(['outing_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_at_bat_batter_id'), 'at_bat', ['batter_id'], unique=False)
    op.create_index(op.f('ix_at_bat_outing_id'), 'at_bat', ['outing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_at_bat_outing_id'), table_name='at_bat')
    op.drop_index(op.f('ix_at_bat_batter_id'), table_name='at_bat')
    op.drop_table('at_bat')
    # ### end Alembic commands ###
