"""empty message

Revision ID: 60efec4356ee
Revises: 5ddf3b6ef78f
Create Date: 2019-12-23 17:40:25.065158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60efec4356ee'
down_revision = '5ddf3b6ef78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch') as batch_op:
        batch_op.drop_index('ix_pitch_outing_id')
        # batch_op.drop_constraint("None", type_='foreignkey')
        batch_op.drop_column('outing_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('outing_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'outing', ['outing_id'], ['id'])
    op.create_index('ix_pitch_outing_id', 'pitch', ['outing_id'], unique=False)
    # ### end Alembic commands ###
