"""empty message

Revision ID: 69cf8f314ee2
Revises: 893740e45072
Create Date: 2020-01-17 17:48:41.109809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cf8f314ee2'
down_revision = '893740e45072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.drop_index('ix_outing_user_id')
        #batch_op.drop_constraint("None", type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outing', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'outing', 'user', ['user_id'], ['id'])
    op.create_index('ix_outing_user_id', 'outing', ['user_id'], unique=False)
    # ### end Alembic commands ###
