"""empty message

Revision ID: 6aa604f63472
Revises: 7c24fefbde0d
Create Date: 2020-01-18 18:31:51.693647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa604f63472'
down_revision = '7c24fefbde0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_outing_game_id'), ['game_id'], unique=False)
        batch_op.create_foreign_key("None", 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outing', type_='foreignkey')
    op.drop_index(op.f('ix_outing_game_id'), table_name='outing')
    op.drop_column('outing', 'game_id')
    # ### end Alembic commands ###
