"""empty message

Revision ID: 6cd1d36fc820
Revises: 0e460bb6bfe1
Create Date: 2019-12-18 20:28:02.780748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd1d36fc820'
down_revision = '0e460bb6bfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.add_column(sa.Column('outing_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_outing_outing_id'), ['outing_id'], unique=False)
        batch_op.create_foreign_key("None1", 'opponent', ['outing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outing', type_='foreignkey')
    op.drop_index(op.f('ix_outing_outing_id'), table_name='outing')
    op.drop_column('outing', 'outing_id')
    # ### end Alembic commands ###
