"""empty message

Revision ID: 72f12a3f2661
Revises: 5c8e3b9bdd7c
Create Date: 2020-03-18 12:08:51.384606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f12a3f2661'
down_revision = '5c8e3b9bdd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season') as batch_op:
        batch_op.drop_index('ix_season_year')
        batch_op.drop_column('year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('year', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_season_year', 'season', ['year'], unique=False)
    # ### end Alembic commands ###
