"""empty message

Revision ID: 75aba5e96f84
Revises: c2ed46cdb845
Create Date: 2019-12-28 23:19:34.453517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aba5e96f84'
down_revision = 'c2ed46cdb845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('retired', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_batter_retired'), 'batter', ['retired'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batter_retired'), table_name='batter')
    op.drop_column('batter', 'retired')
    # ### end Alembic commands ###
