"""update to pitcher table

Revision ID: 85951df46142
Revises: d130999495f5
Create Date: 2020-02-28 10:55:45.976195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85951df46142'
down_revision = 'd130999495f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitcher', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('pitcher', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.add_column('pitcher', sa.Column('number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pitcher_firstname'), 'pitcher', ['firstname'], unique=False)
    op.create_index(op.f('ix_pitcher_lastname'), 'pitcher', ['lastname'], unique=False)
    op.create_index(op.f('ix_pitcher_number'), 'pitcher', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitcher_number'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_lastname'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_firstname'), table_name='pitcher')
    op.drop_column('pitcher', 'number')
    op.drop_column('pitcher', 'lastname')
    op.drop_column('pitcher', 'firstname')
    # ### end Alembic commands ###
