"""empty message

Revision ID: 893740e45072
Revises: 6e27f55f5732
Create Date: 2020-01-17 17:43:19.331115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893740e45072'
down_revision = '6e27f55f5732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.add_column(sa.Column('pitcher_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_outing_pitcher_id'), ['pitcher_id'], unique=False)
        batch_op.create_foreign_key("None", 'pitcher', ['pitcher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outing', type_='foreignkey')
    op.drop_index(op.f('ix_outing_pitcher_id'), table_name='outing')
    op.drop_column('outing', 'pitcher_id')
    # ### end Alembic commands ###
