"""empty message

Revision ID: 8a0a04fc5ebe
Revises: 5d8630dae920
Create Date: 2020-02-06 16:06:32.102736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0a04fc5ebe'
down_revision = '5d8630dae920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video') as batch_op:
        batch_op.drop_index('ix_video_outing_id')
       # batch_op.drop_constraint("None", type_='foreignkey')
        batch_op.drop_column('outing_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('outing_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'video', 'outing', ['outing_id'], ['id'])
    op.create_index('ix_video_outing_id', 'video', ['outing_id'], unique=False)
    # ### end Alembic commands ###
