"""Adding user columns

Revision ID: 941b3e7ebe30
Revises: 1c93cdd10567
Create Date: 2020-06-09 23:33:21.814267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941b3e7ebe30'
down_revision = '1c93cdd10567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_coach', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('current_player', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_current_coach'), 'user', ['current_coach'], unique=False)
    op.create_index(op.f('ix_user_current_player'), 'user', ['current_player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_current_player'), table_name='user')
    op.drop_index(op.f('ix_user_current_coach'), table_name='user')
    op.drop_column('user', 'current_player')
    op.drop_column('user', 'current_coach')
    # ### end Alembic commands ###
