"""empty message

Revision ID: aa91753db216
Revises: 549f9aa3addb
Create Date: 2020-03-09 11:29:58.193916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa91753db216'
down_revision = '549f9aa3addb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video') as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_video_game_id'), ['game_id'], unique=False)
        batch_op.create_foreign_key("None", 'game', ['game_id'], ['id'])
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_index(op.f('ix_video_game_id'), table_name='video')
    op.drop_column('video', 'game_id')
    # ### end Alembic commands ###
