"""update to batter table

Revision ID: ae33a696e946
Revises: 85951df46142
Create Date: 2020-02-28 10:57:15.916416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae33a696e946'
down_revision = '85951df46142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('notes', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_batter_notes'), 'batter', ['notes'], unique=False)
    op.add_column('pitcher', sa.Column('notes', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_pitcher_notes'), 'pitcher', ['notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitcher_notes'), table_name='pitcher')
    op.drop_column('pitcher', 'notes')
    op.drop_index(op.f('ix_batter_notes'), table_name='batter')
    op.drop_column('batter', 'notes')
    # ### end Alembic commands ###
