"""Add ncaa id columns

Revision ID: b47fcd8d3c7c
Revises: 37437611298a
Create Date: 2020-06-10 13:25:34.201161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47fcd8d3c7c'
down_revision = '37437611298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opponent', sa.Column('ncaa_team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_opponent_ncaa_team_id'), 'opponent', ['ncaa_team_id'], unique=False)
    op.add_column('season', sa.Column('ncaa_year_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_season_ncaa_year_id'), 'season', ['ncaa_year_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_ncaa_year_id'), table_name='season')
    op.drop_column('season', 'ncaa_year_id')
    op.drop_index(op.f('ix_opponent_ncaa_team_id'), table_name='opponent')
    op.drop_column('opponent', 'ncaa_team_id')
    # ### end Alembic commands ###
