"""split up batter names

Revision ID: b6f4ce4e16dc
Revises: bb11de8faccc
Create Date: 2020-02-01 14:10:34.814388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f4ce4e16dc'
down_revision = 'bb11de8faccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('batter', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batter', 'lastname')
    op.drop_column('batter', 'firstname')
    # ### end Alembic commands ###
