"""empty message

Revision ID: ba87d5269549
Revises: d6914ff44f09
Create Date: 2019-12-25 00:39:07.459749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba87d5269549'
down_revision = 'd6914ff44f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch') as batch_op:
        batch_op.add_column(sa.Column('batter_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_pitch_batter_id'), ['batter_id'], unique=False)
        batch_op.drop_index('ix_pitch_batter_hand')
        batch_op.create_foreign_key('None', 'batter', ['batter_id'], ['id'])
        batch_op.drop_column('batter_hand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('batter_hand', sa.VARCHAR(length=16), nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_index('ix_pitch_batter_hand', 'pitch', ['batter_hand'], unique=False)
    op.drop_index(op.f('ix_pitch_batter_id'), table_name='pitch')
    op.drop_column('pitch', 'batter_id')
    # ### end Alembic commands ###
