"""added pitcher r table

Revision ID: c0090f308707
Revises: 411beb54b27b
Create Date: 2020-01-17 17:03:02.631185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0090f308707'
down_revision = '411beb54b27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('throws', sa.String(length=64), nullable=True),
    sa.Column('grad_year', sa.String(length=8), nullable=True),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitcher_grad_year'), 'pitcher', ['grad_year'], unique=False)
    op.create_index(op.f('ix_pitcher_name'), 'pitcher', ['name'], unique=False)
    op.create_index(op.f('ix_pitcher_opponent_id'), 'pitcher', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_pitcher_retired'), 'pitcher', ['retired'], unique=False)
    op.create_index(op.f('ix_pitcher_throws'), 'pitcher', ['throws'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitcher_throws'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_retired'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_opponent_id'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_name'), table_name='pitcher')
    op.drop_index(op.f('ix_pitcher_grad_year'), table_name='pitcher')
    op.drop_table('pitcher')
    # ### end Alembic commands ###
