"""empty message

Revision ID: c2ed46cdb845
Revises: ba87d5269549
Create Date: 2019-12-26 10:01:42.564949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ed46cdb845'
down_revision = 'ba87d5269549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('grad_year', sa.String(length=8), nullable=True))
        batch_op.create_index(op.f('ix_user_grad_year'), ['grad_year'], unique=False)
        batch_op.drop_index('ix_user_year')
        batch_op.drop_column('year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('year', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_user_year', 'user', ['year'], unique=False)
    op.drop_index(op.f('ix_user_grad_year'), table_name='user')
    op.drop_column('user', 'grad_year')
    # ### end Alembic commands ###
