"""empty message

Revision ID: ced51a5bb6ae
Revises: e1f8d412e0d4
Create Date: 2020-02-06 16:10:54.769501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced51a5bb6ae'
down_revision = 'e1f8d412e0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batter') as batch_op:
        batch_op.drop_index('ix_video_outing_id')
       # batch_op.drop_constraint("None", type_='foreignkey')
        batch_op.drop_column('outing_id')

    with op.batch_alter_table('video') as batch_op:
        batch_op.add_column(sa.Column('outing_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_video_outing_id'), ['outing_id'], unique=False)
        batch_op.create_foreign_key("None", 'outing', ['outing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_index(op.f('ix_video_outing_id'), table_name='video')
    op.drop_column('video', 'outing_id')
    op.add_column('batter', sa.Column('outing_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'batter', 'outing', ['outing_id'], ['id'])
    op.create_index('ix_video_outing_id', 'batter', ['outing_id'], unique=False)
    # ### end Alembic commands ###
