"""empty message

Revision ID: cf37f26ca26f
Revises: aa91753db216
Create Date: 2020-03-18 12:05:50.271969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf37f26ca26f'
down_revision = 'aa91753db216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season') as batch_op:
        batch_op.drop_index('ix_season_semester')
        batch_op.drop_column('semester')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('semester', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_season_semester', 'season', ['semester'], unique=False)
    # ### end Alembic commands ###
