"""empty message

Revision ID: d130999495f5
Revises: 0a8915b088ef
Create Date: 2020-02-22 09:21:54.517893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd130999495f5'
down_revision = '0a8915b088ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('initials', sa.String(length=8), nullable=True))
    op.add_column('batter', sa.Column('number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_batter_initials'), 'batter', ['initials'], unique=False)
    op.create_index(op.f('ix_batter_number'), 'batter', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batter_number'), table_name='batter')
    op.drop_index(op.f('ix_batter_initials'), table_name='batter')
    op.drop_column('batter', 'number')
    op.drop_column('batter', 'initials')
    # ### end Alembic commands ###
