"""empty message

Revision ID: d381b1febff3
Revises: a7275705df1d
Create Date: 2021-01-08 12:58:03.733310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd381b1febff3'
down_revision = 'a7275705df1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column(
            'infielder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column(
            'outfielder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column(
            'pitcher', sa.Boolean(), nullable=True))
        batch_op.create_index(op.f('ix_user_infielder'), [
                              'infielder'], unique=False)
        batch_op.create_index(op.f('ix_user_outfielder'), [
                              'outfielder'], unique=False)
        batch_op.create_index(op.f('ix_user_pitcher'), [
                              'pitcher'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pitcher'), table_name='user')
    op.drop_index(op.f('ix_user_outfielder'), table_name='user')
    op.drop_index(op.f('ix_user_infielder'), table_name='user')
    op.drop_column('user', 'pitcher')
    op.drop_column('user', 'outfielder')
    op.drop_column('user', 'infielder')
    op.drop_index(op.f('ix_opponent_mascot'), table_name='opponent')
    # ### end Alembic commands ###
