"""empty message

Revision ID: d6914ff44f09
Revises: 0a42b3c6224d
Create Date: 2019-12-25 00:36:19.933511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6914ff44f09'
down_revision = '0a42b3c6224d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch') as batch_op:
        batch_op.drop_index('ix_pitch_batter_id')
        batch_op.drop_column('batter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('batter_id', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_pitch_batter_id', 'pitch', ['batter_id'], unique=False)
    # ### end Alembic commands ###
