"""add retired column to user

Revision ID: d6c6ee5ad7e0
Revises: 75aba5e96f84
Create Date: 2019-12-29 15:58:49.416420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c6ee5ad7e0'
down_revision = '75aba5e96f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('retired', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_retired'), 'user', ['retired'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_retired'), table_name='user')
    op.drop_column('user', 'retired')
    # ### end Alembic commands ###
