"""add hit hard column

Revision ID: db376de83655
Revises: dedaeb10173a
Create Date: 2020-02-01 14:49:25.260520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db376de83655'
down_revision = 'dedaeb10173a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('hit_hard', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_pitch_hit_hard'), 'pitch', ['hit_hard'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_hit_hard'), table_name='pitch')
    op.drop_column('pitch', 'hit_hard')
    # ### end Alembic commands ###
