"""delete batter name

Revision ID: dedaeb10173a
Revises: b6f4ce4e16dc
Create Date: 2020-02-01 14:15:33.737295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedaeb10173a'
down_revision = 'b6f4ce4e16dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batter') as batch_op:
        batch_op.drop_index('ix_batter_name')
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batter', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_batter_name', 'batter', ['name'], unique=False)
    # ### end Alembic commands ###
