"""empty message

Revision ID: e4502b2cd507
Revises: 24d363db59ac
Create Date: 2019-12-18 12:12:07.909412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4502b2cd507'
down_revision = '24d363db59ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing') as batch_op:
        batch_op.drop_index('ix_outing_season_id')
        batch_op.drop_column('season_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outing', sa.Column('season_id', sa.INTEGER(), nullable=True))
    op.create_index('ix_outing_season_id', 'outing', ['season_id'], unique=False)
    # ### end Alembic commands ###
