"""empty message

Revision ID: ff66a7bfae26
Revises: 53b5309c617a
Create Date: 2020-01-18 17:56:12.634378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff66a7bfae26'
down_revision = '53b5309c617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_index('ix_user_grad_year')
        batch_op.drop_column('grad_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('grad_year', sa.VARCHAR(length=8), nullable=True))
    op.create_index('ix_user_grad_year', 'user', ['grad_year'], unique=False)
    # ### end Alembic commands ###
